import { Routes } from '@angular/router';
import { AttributeDirectiveComponent } from '../attribute-directive/attribute-directive.component';
import { ComponentInteractionP2Component } from '../component-interaction-p2/component-interaction-p2.component';
import { ComponentInteractionComponent } from '../component-interaction/component-interaction.component';
import { ContentChildComponent } from '../content-child/content-child.component';
import { ContentProjectionComponent } from '../content-projection/content-projection.component';
import { DataBindingComponent } from '../data-binding/data-binding.component';
import { DependenceInjectionComponent } from '../dependence-injection/dependence-injection.component';
import { DynamicComponentComponent } from '../dynamic-component/dynamic-component.component';
import { IntroDependenceInjectionComponent } from '../intro-dependence-injection/intro-dependence-injection.component';
import { NgTemplateComponent } from '../ng-template/ng-template.component';
import { PipeComponent } from '../pipe/pipe.component';
import { StructureDirectiveComponent } from '../structure-directive/structure-directive.component';
import { TemplateVariableComponent } from '../template-variable/template-variable.component';
import { TypescriptAdvTypeComponent } from '../typescript-adv-type/typescript-adv-type.component';
import { TypescriptDataTypeComponent } from '../typescript-data-type/typescript-data-type.component';

export const COMMON_CONCEPT_ROUTES: Routes = [
  { path: 'data-binding', component: DataBindingComponent },
  { path: 'structure-directive', component: StructureDirectiveComponent },
  { path: 'attribute-directive', component: AttributeDirectiveComponent },
  { path: 'component-interaction-p1', component: ComponentInteractionComponent },
  { path: 'component-interaction-p2', component: ComponentInteractionP2Component },
  { path: 'template-variable', component: TemplateVariableComponent },
  { path: 'typescript-data-type', component: TypescriptDataTypeComponent },
  { path: 'typescript-adv-type', component: TypescriptAdvTypeComponent },
  { path: 'content-projection', component: ContentProjectionComponent },
  { path: 'ng-template', component: NgTemplateComponent },
  { path: 'intro-dependency-injection', component: IntroDependenceInjectionComponent },
  { path: 'dependency-injection', component: DependenceInjectionComponent },
  { path: 'content-child', component: ContentChildComponent },
  { path: 'pipe', component: PipeComponent },
  { path: 'dynamic-component', component: DynamicComponentComponent },
];
